
package magento;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "MagentoService", targetNamespace = "urn:Magento", wsdlLocation = "http://www.yourstore.com/magento/api/v2_soap?wsdl=1")
public class MagentoService
    extends Service
{

    private final static URL MAGENTOSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(magento.MagentoService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = magento.MagentoService.class.getResource(".");
            url = new URL(baseUrl, "http://www.yourstore.com/magento/api/v2_soap?wsdl=1");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://www.yourstore.com/magento/api/v2_soap?wsdl=1', retrying as a local file");
            logger.warning(e.getMessage());
        }
        MAGENTOSERVICE_WSDL_LOCATION = url;
    }

    public MagentoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MagentoService() {
        super(MAGENTOSERVICE_WSDL_LOCATION, new QName("urn:Magento", "MagentoService"));
    }

    /**
     * 
     * @return
     *     returns MageApiModelServerWsiHandlerPortType
     */
    @WebEndpoint(name = "Mage_Api_Model_Server_Wsi_HandlerPort")
    public MageApiModelServerWsiHandlerPortType getMageApiModelServerWsiHandlerPort() {
        return super.getPort(new QName("urn:Magento", "Mage_Api_Model_Server_Wsi_HandlerPort"), MageApiModelServerWsiHandlerPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MageApiModelServerWsiHandlerPortType
     */
    @WebEndpoint(name = "Mage_Api_Model_Server_Wsi_HandlerPort")
    public MageApiModelServerWsiHandlerPortType getMageApiModelServerWsiHandlerPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:Magento", "Mage_Api_Model_Server_Wsi_HandlerPort"), MageApiModelServerWsiHandlerPortType.class, features);
    }

}
