
package magento;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Mage_Api_Model_Server_Wsi_HandlerPortType", targetNamespace = "urn:Magento")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MageApiModelServerWsiHandlerPortType {


    /**
     * Call api functionality
     * 
     * @param parameters
     * @return
     *     returns magento.CallResponseParam
     */
    @WebMethod
    @WebResult(name = "callResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CallResponseParam call(
        @WebParam(name = "callParam", targetNamespace = "urn:Magento", partName = "parameters")
        CallParam parameters);

    /**
     * Multiple calls of resource functionality
     * 
     * @param parameters
     * @return
     *     returns magento.MultiCallResponseParam
     */
    @WebMethod
    @WebResult(name = "multiCallResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public MultiCallResponseParam multiCall(
        @WebParam(name = "multiCallParam", targetNamespace = "urn:Magento", partName = "parameters")
        MultiCallParam parameters);

    /**
     * End web service session
     * 
     * @param parameters
     * @return
     *     returns magento.EndSessionResponseParam
     */
    @WebMethod
    @WebResult(name = "endSessionResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public EndSessionResponseParam endSession(
        @WebParam(name = "endSessionParam", targetNamespace = "urn:Magento", partName = "parameters")
        EndSessionParam parameters);

    /**
     * Login user and retrive session id
     * 
     * @param parameters
     * @return
     *     returns magento.LoginResponseParam
     */
    @WebMethod
    @WebResult(name = "loginResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public LoginResponseParam login(
        @WebParam(name = "loginParam", targetNamespace = "urn:Magento", partName = "parameters")
        LoginParam parameters);

    /**
     * Start web service session
     * 
     * @return
     *     returns magento.StartSessionResponseParam
     */
    @WebMethod
    @WebResult(name = "startSessionResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public StartSessionResponseParam startSession();

    /**
     * List of available resources
     * 
     * @param parameters
     * @return
     *     returns magento.ResourcesResponseParam
     */
    @WebMethod
    @WebResult(name = "resourcesResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public ResourcesResponseParam resources(
        @WebParam(name = "resourcesRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        ResourcesRequestParam parameters);

    /**
     * List of global faults
     * 
     * @param parameters
     * @return
     *     returns magento.GlobalFaultsResponseParam
     */
    @WebMethod
    @WebResult(name = "globalFaultsResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public GlobalFaultsResponseParam globalFaults(
        @WebParam(name = "globalFaultsParam", targetNamespace = "urn:Magento", partName = "parameters")
        GlobalFaultsParam parameters);

    /**
     * List of resource faults
     * 
     * @param parameters
     * @return
     *     returns magento.ResourceFaultsResponseParam
     */
    @WebMethod
    @WebResult(name = "resourceFaultsResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public ResourceFaultsResponseParam resourceFaults(
        @WebParam(name = "resourceFaultsParam", targetNamespace = "urn:Magento", partName = "parameters")
        ResourceFaultsParam parameters);

    /**
     * List of stores
     * 
     * @param parameters
     * @return
     *     returns magento.StoreListResponseParam
     */
    @WebMethod
    @WebResult(name = "storeListResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public StoreListResponseParam storeList(
        @WebParam(name = "storeListRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        StoreListRequestParam parameters);

    /**
     * Store view info
     * 
     * @param parameters
     * @return
     *     returns magento.StoreInfoResponseParam
     */
    @WebMethod
    @WebResult(name = "storeInfoResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public StoreInfoResponseParam storeInfo(
        @WebParam(name = "storeInfoRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        StoreInfoRequestParam parameters);

    /**
     * Info about current Magento installation
     * 
     * @param parameters
     * @return
     *     returns magento.MagentoInfoResponseParam
     */
    @WebMethod
    @WebResult(name = "magentoInfoResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public MagentoInfoResponseParam magentoInfo(
        @WebParam(name = "magentoInfoRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        MagentoInfoRequestParam parameters);

    /**
     * List of countries
     * 
     * @param parameters
     * @return
     *     returns magento.DirectoryCountryListResponseParam
     */
    @WebMethod
    @WebResult(name = "directoryCountryListResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public DirectoryCountryListResponseParam directoryCountryList(
        @WebParam(name = "directoryCountryListRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        DirectoryCountryListRequestParam parameters);

    /**
     * List of regions in specified country
     * 
     * @param parameters
     * @return
     *     returns magento.DirectoryRegionListResponseParam
     */
    @WebMethod
    @WebResult(name = "directoryRegionListResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public DirectoryRegionListResponseParam directoryRegionList(
        @WebParam(name = "directoryRegionListRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        DirectoryRegionListRequestParam parameters);

    /**
     * Retrieve customers
     * 
     * @param parameters
     * @return
     *     returns magento.CustomerCustomerListResponseParam
     */
    @WebMethod
    @WebResult(name = "customerCustomerListResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CustomerCustomerListResponseParam customerCustomerList(
        @WebParam(name = "customerCustomerListRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CustomerCustomerListRequestParam parameters);

    /**
     * Create customer
     * 
     * @param parameters
     * @return
     *     returns magento.CustomerCustomerCreateResponseParam
     */
    @WebMethod
    @WebResult(name = "customerCustomerCreateResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CustomerCustomerCreateResponseParam customerCustomerCreate(
        @WebParam(name = "customerCustomerCreateRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CustomerCustomerCreateRequestParam parameters);

    /**
     * Retrieve customer data
     * 
     * @param parameters
     * @return
     *     returns magento.CustomerCustomerInfoResponseParam
     */
    @WebMethod
    @WebResult(name = "customerCustomerInfoResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CustomerCustomerInfoResponseParam customerCustomerInfo(
        @WebParam(name = "customerCustomerInfoRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CustomerCustomerInfoRequestParam parameters);

    /**
     * Update customer data
     * 
     * @param parameters
     * @return
     *     returns magento.CustomerCustomerUpdateResponseParam
     */
    @WebMethod
    @WebResult(name = "customerCustomerUpdateResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CustomerCustomerUpdateResponseParam customerCustomerUpdate(
        @WebParam(name = "customerCustomerUpdateRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CustomerCustomerUpdateRequestParam parameters);

    /**
     * Delete customer
     * 
     * @param parameters
     * @return
     *     returns magento.CustomerCustomerDeleteResponseParam
     */
    @WebMethod
    @WebResult(name = "customerCustomerDeleteResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CustomerCustomerDeleteResponseParam customerCustomerDelete(
        @WebParam(name = "customerCustomerDeleteRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CustomerCustomerDeleteRequestParam parameters);

    /**
     * Retrieve customer groups
     * 
     * @param parameters
     * @return
     *     returns magento.CustomerGroupListResponseParam
     */
    @WebMethod
    @WebResult(name = "customerGroupListResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CustomerGroupListResponseParam customerGroupList(
        @WebParam(name = "customerGroupListRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CustomerGroupListRequestParam parameters);

    /**
     * Retrieve customer addresses
     * 
     * @param parameters
     * @return
     *     returns magento.CustomerAddressListResponseParam
     */
    @WebMethod
    @WebResult(name = "customerAddressListResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CustomerAddressListResponseParam customerAddressList(
        @WebParam(name = "customerAddressListRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CustomerAddressListRequestParam parameters);

    /**
     * Create customer address
     * 
     * @param parameters
     * @return
     *     returns magento.CustomerAddressCreateResponseParam
     */
    @WebMethod
    @WebResult(name = "customerAddressCreateResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CustomerAddressCreateResponseParam customerAddressCreate(
        @WebParam(name = "customerAddressCreateRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CustomerAddressCreateRequestParam parameters);

    /**
     * Retrieve customer address data
     * 
     * @param parameters
     * @return
     *     returns magento.CustomerAddressInfoResponseParam
     */
    @WebMethod
    @WebResult(name = "customerAddressInfoResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CustomerAddressInfoResponseParam customerAddressInfo(
        @WebParam(name = "customerAddressInfoRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CustomerAddressInfoRequestParam parameters);

    /**
     * Update customer address data
     * 
     * @param parameters
     * @return
     *     returns magento.CustomerAddressUpdateResponseParam
     */
    @WebMethod
    @WebResult(name = "customerAddressUpdateResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CustomerAddressUpdateResponseParam customerAddressUpdate(
        @WebParam(name = "customerAddressUpdateRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CustomerAddressUpdateRequestParam parameters);

    /**
     * Delete customer address
     * 
     * @param parameters
     * @return
     *     returns magento.CustomerAddressDeleteResponseParam
     */
    @WebMethod
    @WebResult(name = "customerAddressDeleteResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CustomerAddressDeleteResponseParam customerAddressDelete(
        @WebParam(name = "customerAddressDeleteRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CustomerAddressDeleteRequestParam parameters);

    /**
     * Set_Get current store view
     * 
     * @param parameters
     * @return
     *     returns magento.CatalogCategoryCurrentStoreResponseParam
     */
    @WebMethod
    @WebResult(name = "catalogCategoryCurrentStoreResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CatalogCategoryCurrentStoreResponseParam catalogCategoryCurrentStore(
        @WebParam(name = "catalogCategoryCurrentStoreRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CatalogCategoryCurrentStoreRequestParam parameters);

    /**
     * Retrieve hierarchical tree of categories.
     * 
     * @param parameters
     * @return
     *     returns magento.CatalogCategoryTreeResponseParam
     */
    @WebMethod
    @WebResult(name = "catalogCategoryTreeResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CatalogCategoryTreeResponseParam catalogCategoryTree(
        @WebParam(name = "catalogCategoryTreeRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CatalogCategoryTreeRequestParam parameters);

    /**
     * Retrieve hierarchical tree of categories.
     * 
     * @param parameters
     * @return
     *     returns magento.CatalogCategoryLevelResponseParam
     */
    @WebMethod
    @WebResult(name = "catalogCategoryLevelResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CatalogCategoryLevelResponseParam catalogCategoryLevel(
        @WebParam(name = "catalogCategoryLevelRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CatalogCategoryLevelRequestParam parameters);

    /**
     * Retrieve hierarchical tree of categories.
     * 
     * @param parameters
     * @return
     *     returns magento.CatalogCategoryInfoResponseParam
     */
    @WebMethod
    @WebResult(name = "catalogCategoryInfoResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CatalogCategoryInfoResponseParam catalogCategoryInfo(
        @WebParam(name = "catalogCategoryInfoRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CatalogCategoryInfoRequestParam parameters);

    /**
     * Create new category and return its id.
     * 
     * @param parameters
     * @return
     *     returns magento.CatalogCategoryCreateResponseParam
     */
    @WebMethod
    @WebResult(name = "catalogCategoryCreateResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CatalogCategoryCreateResponseParam catalogCategoryCreate(
        @WebParam(name = "catalogCategoryCreateRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CatalogCategoryCreateRequestParam parameters);

    /**
     * Update category
     * 
     * @param parameters
     * @return
     *     returns magento.CatalogCategoryUpdateResponseParam
     */
    @WebMethod
    @WebResult(name = "catalogCategoryUpdateResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CatalogCategoryUpdateResponseParam catalogCategoryUpdate(
        @WebParam(name = "catalogCategoryUpdateRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CatalogCategoryUpdateRequestParam parameters);

    /**
     * Move category in tree
     * 
     * @param parameters
     * @return
     *     returns magento.CatalogCategoryMoveResponseParam
     */
    @WebMethod
    @WebResult(name = "catalogCategoryMoveResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CatalogCategoryMoveResponseParam catalogCategoryMove(
        @WebParam(name = "catalogCategoryMoveRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CatalogCategoryMoveRequestParam parameters);

    /**
     * Delete category
     * 
     * @param parameters
     * @return
     *     returns magento.CatalogCategoryDeleteResponseParam
     */
    @WebMethod
    @WebResult(name = "catalogCategoryDeleteResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CatalogCategoryDeleteResponseParam catalogCategoryDelete(
        @WebParam(name = "catalogCategoryDeleteRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CatalogCategoryDeleteRequestParam parameters);

    /**
     * Retrieve list of assigned products
     * 
     * @param parameters
     * @return
     *     returns magento.CatalogCategoryAssignedProductsResponseParam
     */
    @WebMethod
    @WebResult(name = "catalogCategoryAssignedProductsResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CatalogCategoryAssignedProductsResponseParam catalogCategoryAssignedProducts(
        @WebParam(name = "catalogCategoryAssignedProductsRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CatalogCategoryAssignedProductsRequestParam parameters);

    /**
     * Assign product to category
     * 
     * @param parameters
     * @return
     *     returns magento.CatalogCategoryAssignProductResponseParam
     */
    @WebMethod
    @WebResult(name = "catalogCategoryAssignProductResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CatalogCategoryAssignProductResponseParam catalogCategoryAssignProduct(
        @WebParam(name = "catalogCategoryAssignProductRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CatalogCategoryAssignProductRequestParam parameters);

    /**
     * Update assigned product
     * 
     * @param parameters
     * @return
     *     returns magento.CatalogCategoryUpdateProductResponseParam
     */
    @WebMethod
    @WebResult(name = "catalogCategoryUpdateProductResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CatalogCategoryUpdateProductResponseParam catalogCategoryUpdateProduct(
        @WebParam(name = "catalogCategoryUpdateProductRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CatalogCategoryUpdateProductRequestParam parameters);

    /**
     * Remove product assignment from category
     * 
     * @param parameters
     * @return
     *     returns magento.CatalogCategoryRemoveProductResponseParam
     */
    @WebMethod
    @WebResult(name = "catalogCategoryRemoveProductResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CatalogCategoryRemoveProductResponseParam catalogCategoryRemoveProduct(
        @WebParam(name = "catalogCategoryRemoveProductRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CatalogCategoryRemoveProductRequestParam parameters);

    /**
     * Set/Get current store view
     * 
     * @param parameters
     * @return
     *     returns magento.CatalogProductCurrentStoreResponseParam
     */
    @WebMethod
    @WebResult(name = "catalogProductCurrentStoreResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CatalogProductCurrentStoreResponseParam catalogProductCurrentStore(
        @WebParam(name = "catalogProductCurrentStoreRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CatalogProductCurrentStoreRequestParam parameters);

    /**
     * Retrieve products list by filters
     * 
     * @param parameters
     * @return
     *     returns magento.CatalogProductListResponseParam
     */
    @WebMethod
    @WebResult(name = "catalogProductListResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CatalogProductListResponseParam catalogProductList(
        @WebParam(name = "catalogProductListRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CatalogProductListRequestParam parameters);

    /**
     * Retrieve product
     * 
     * @param parameters
     * @return
     *     returns magento.CatalogProductInfoResponseParam
     */
    @WebMethod
    @WebResult(name = "catalogProductInfoResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CatalogProductInfoResponseParam catalogProductInfo(
        @WebParam(name = "catalogProductInfoRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CatalogProductInfoRequestParam parameters);

    /**
     * Create new product and return product id
     * 
     * @param parameters
     * @return
     *     returns magento.CatalogProductCreateResponseParam
     */
    @WebMethod
    @WebResult(name = "catalogProductCreateResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CatalogProductCreateResponseParam catalogProductCreate(
        @WebParam(name = "catalogProductCreateRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CatalogProductCreateRequestParam parameters);

    /**
     * Update product
     * 
     * @param parameters
     * @return
     *     returns magento.CatalogProductUpdateResponseParam
     */
    @WebMethod
    @WebResult(name = "catalogProductUpdateResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CatalogProductUpdateResponseParam catalogProductUpdate(
        @WebParam(name = "catalogProductUpdateRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CatalogProductUpdateRequestParam parameters);

    /**
     * Update product special price
     * 
     * @param parameters
     * @return
     *     returns magento.CatalogProductSetSpecialPriceResponseParam
     */
    @WebMethod
    @WebResult(name = "catalogProductSetSpecialPriceResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CatalogProductSetSpecialPriceResponseParam catalogProductSetSpecialPrice(
        @WebParam(name = "catalogProductSetSpecialPriceRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CatalogProductSetSpecialPriceRequestParam parameters);

    /**
     * Get product special price data
     * 
     * @param parameters
     * @return
     *     returns magento.CatalogProductGetSpecialPriceResponseParam
     */
    @WebMethod
    @WebResult(name = "catalogProductGetSpecialPriceResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CatalogProductGetSpecialPriceResponseParam catalogProductGetSpecialPrice(
        @WebParam(name = "catalogProductGetSpecialPriceRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CatalogProductGetSpecialPriceRequestParam parameters);

    /**
     * Delete product
     * 
     * @param parameters
     * @return
     *     returns magento.CatalogProductDeleteResponseParam
     */
    @WebMethod
    @WebResult(name = "catalogProductDeleteResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CatalogProductDeleteResponseParam catalogProductDelete(
        @WebParam(name = "catalogProductDeleteRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CatalogProductDeleteRequestParam parameters);

    /**
     * Set/Get current store view
     * 
     * @param parameters
     * @return
     *     returns magento.CatalogProductAttributeCurrentStoreResponseParam
     */
    @WebMethod
    @WebResult(name = "catalogProductAttributeCurrentStoreResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CatalogProductAttributeCurrentStoreResponseParam catalogProductAttributeCurrentStore(
        @WebParam(name = "catalogProductAttributeCurrentStoreRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CatalogProductAttributeCurrentStoreRequestParam parameters);

    /**
     * Retrieve attribute list
     * 
     * @param parameters
     * @return
     *     returns magento.CatalogProductAttributeListResponseParam
     */
    @WebMethod
    @WebResult(name = "catalogProductAttributeListResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CatalogProductAttributeListResponseParam catalogProductAttributeList(
        @WebParam(name = "catalogProductAttributeListRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CatalogProductAttributeListRequestParam parameters);

    /**
     * Retrieve attribute options
     * 
     * @param parameters
     * @return
     *     returns magento.CatalogProductAttributeOptionsResponseParam
     */
    @WebMethod
    @WebResult(name = "catalogProductAttributeOptionsResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CatalogProductAttributeOptionsResponseParam catalogProductAttributeOptions(
        @WebParam(name = "catalogProductAttributeOptionsRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CatalogProductAttributeOptionsRequestParam parameters);

    /**
     * Add new custom option into product
     * 
     * @param parameters
     * @return
     *     returns magento.CatalogProductCustomOptionAddResponseParam
     */
    @WebMethod
    @WebResult(name = "catalogProductCustomOptionAddResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CatalogProductCustomOptionAddResponseParam catalogProductCustomOptionAdd(
        @WebParam(name = "catalogProductCustomOptionAddRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CatalogProductCustomOptionAddRequestParam parameters);

    /**
     * Update product custom option
     * 
     * @param parameters
     * @return
     *     returns magento.CatalogProductCustomOptionUpdateResponseParam
     */
    @WebMethod
    @WebResult(name = "catalogProductCustomOptionUpdateResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CatalogProductCustomOptionUpdateResponseParam catalogProductCustomOptionUpdate(
        @WebParam(name = "catalogProductCustomOptionUpdateRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CatalogProductCustomOptionUpdateRequestParam parameters);

    /**
     * Get list of available custom option types 
     * 
     * @param parameters
     * @return
     *     returns magento.CatalogProductCustomOptionTypesResponseParam
     */
    @WebMethod
    @WebResult(name = "catalogProductCustomOptionTypesResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CatalogProductCustomOptionTypesResponseParam catalogProductCustomOptionTypes(
        @WebParam(name = "catalogProductCustomOptionTypesRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CatalogProductCustomOptionTypesRequestParam parameters);

    /**
     * Retrieve list of product custom options
     * 
     * @param parameters
     * @return
     *     returns magento.CatalogProductCustomOptionListResponseParam
     */
    @WebMethod
    @WebResult(name = "catalogProductCustomOptionListResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CatalogProductCustomOptionListResponseParam catalogProductCustomOptionList(
        @WebParam(name = "catalogProductCustomOptionListRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CatalogProductCustomOptionListRequestParam parameters);

    /**
     * Get full information about custom option in product
     * 
     * @param parameters
     * @return
     *     returns magento.CatalogProductCustomOptionInfoResponseParam
     */
    @WebMethod
    @WebResult(name = "catalogProductCustomOptionInfoResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CatalogProductCustomOptionInfoResponseParam catalogProductCustomOptionInfo(
        @WebParam(name = "catalogProductCustomOptionInfoRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CatalogProductCustomOptionInfoRequestParam parameters);

    /**
     * Remove custom option
     * 
     * @param parameters
     * @return
     *     returns magento.CatalogProductCustomOptionRemoveResponseParam
     */
    @WebMethod
    @WebResult(name = "catalogProductCustomOptionRemoveResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CatalogProductCustomOptionRemoveResponseParam catalogProductCustomOptionRemove(
        @WebParam(name = "catalogProductCustomOptionRemoveRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CatalogProductCustomOptionRemoveRequestParam parameters);

    /**
     * Retrieve custom option values list
     * 
     * @param parameters
     * @return
     *     returns magento.CatalogProductCustomOptionValueListResponseParam
     */
    @WebMethod
    @WebResult(name = "catalogProductCustomOptionValueListResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CatalogProductCustomOptionValueListResponseParam catalogProductCustomOptionValueList(
        @WebParam(name = "catalogProductCustomOptionValueListRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CatalogProductCustomOptionValueListRequestParam parameters);

    /**
     * Retrieve custom option value info
     * 
     * @param parameters
     * @return
     *     returns magento.CatalogProductCustomOptionValueInfoResponseParam
     */
    @WebMethod
    @WebResult(name = "catalogProductCustomOptionValueInfoResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CatalogProductCustomOptionValueInfoResponseParam catalogProductCustomOptionValueInfo(
        @WebParam(name = "catalogProductCustomOptionValueInfoRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CatalogProductCustomOptionValueInfoRequestParam parameters);

    /**
     * Add new custom option values
     * 
     * @param parameters
     * @return
     *     returns magento.CatalogProductCustomOptionValueAddResponseParam
     */
    @WebMethod
    @WebResult(name = "catalogProductCustomOptionValueAddResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CatalogProductCustomOptionValueAddResponseParam catalogProductCustomOptionValueAdd(
        @WebParam(name = "catalogProductCustomOptionValueAddRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CatalogProductCustomOptionValueAddRequestParam parameters);

    /**
     * Update custom option value
     * 
     * @param parameters
     * @return
     *     returns magento.CatalogProductCustomOptionValueUpdateResponseParam
     */
    @WebMethod
    @WebResult(name = "catalogProductCustomOptionValueUpdateResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CatalogProductCustomOptionValueUpdateResponseParam catalogProductCustomOptionValueUpdate(
        @WebParam(name = "catalogProductCustomOptionValueUpdateRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CatalogProductCustomOptionValueUpdateRequestParam parameters);

    /**
     * Remove value from custom option
     * 
     * @param parameters
     * @return
     *     returns magento.CatalogProductCustomOptionValueRemoveResponseParam
     */
    @WebMethod
    @WebResult(name = "catalogProductCustomOptionValueRemoveResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CatalogProductCustomOptionValueRemoveResponseParam catalogProductCustomOptionValueRemove(
        @WebParam(name = "catalogProductCustomOptionValueRemoveRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CatalogProductCustomOptionValueRemoveRequestParam parameters);

    /**
     * Create product attribute set based on another set
     * 
     * @param parameters
     * @return
     *     returns magento.CatalogProductAttributeSetCreateResponseParam
     */
    @WebMethod
    @WebResult(name = "catalogProductAttributeSetCreateResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CatalogProductAttributeSetCreateResponseParam catalogProductAttributeSetCreate(
        @WebParam(name = "catalogProductAttributeSetCreateRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CatalogProductAttributeSetCreateRequestParam parameters);

    /**
     * Remove product attribute set
     * 
     * @param parameters
     * @return
     *     returns magento.CatalogProductAttributeSetRemoveResponseParam
     */
    @WebMethod
    @WebResult(name = "catalogProductAttributeSetRemoveResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CatalogProductAttributeSetRemoveResponseParam catalogProductAttributeSetRemove(
        @WebParam(name = "catalogProductAttributeSetRemoveRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CatalogProductAttributeSetRemoveRequestParam parameters);

    /**
     * Retrieve product attribute sets
     * 
     * @param parameters
     * @return
     *     returns magento.CatalogProductAttributeSetListResponseParam
     */
    @WebMethod
    @WebResult(name = "catalogProductAttributeSetListResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CatalogProductAttributeSetListResponseParam catalogProductAttributeSetList(
        @WebParam(name = "catalogProductAttributeSetListRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CatalogProductAttributeSetListRequestParam parameters);

    /**
     * Add attribute into attribute set
     * 
     * @param parameters
     * @return
     *     returns magento.CatalogProductAttributeSetAttributeAddResponseParam
     */
    @WebMethod
    @WebResult(name = "catalogProductAttributeSetAttributeAddResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CatalogProductAttributeSetAttributeAddResponseParam catalogProductAttributeSetAttributeAdd(
        @WebParam(name = "catalogProductAttributeSetAttributeAddRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CatalogProductAttributeSetAttributeAddRequestParam parameters);

    /**
     * Remove attribute from attribute set
     * 
     * @param parameters
     * @return
     *     returns magento.CatalogProductAttributeSetAttributeRemoveResponseParam
     */
    @WebMethod
    @WebResult(name = "catalogProductAttributeSetAttributeRemoveResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CatalogProductAttributeSetAttributeRemoveResponseParam catalogProductAttributeSetAttributeRemove(
        @WebParam(name = "catalogProductAttributeSetAttributeRemoveRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CatalogProductAttributeSetAttributeRemoveRequestParam parameters);

    /**
     * Create group within existing attribute set
     * 
     * @param parameters
     * @return
     *     returns magento.CatalogProductAttributeSetGroupAddResponseParam
     */
    @WebMethod
    @WebResult(name = "catalogProductAttributeSetGroupAddResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CatalogProductAttributeSetGroupAddResponseParam catalogProductAttributeSetGroupAdd(
        @WebParam(name = "catalogProductAttributeSetGroupAddRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CatalogProductAttributeSetGroupAddRequestParam parameters);

    /**
     * Rename existing group
     * 
     * @param parameters
     * @return
     *     returns magento.CatalogProductAttributeSetGroupRenameResponseParam
     */
    @WebMethod
    @WebResult(name = "catalogProductAttributeSetGroupRenameResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CatalogProductAttributeSetGroupRenameResponseParam catalogProductAttributeSetGroupRename(
        @WebParam(name = "catalogProductAttributeSetGroupRenameRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CatalogProductAttributeSetGroupRenameRequestParam parameters);

    /**
     * Remove group from attribute set
     * 
     * @param parameters
     * @return
     *     returns magento.CatalogProductAttributeSetGroupRemoveResponseParam
     */
    @WebMethod
    @WebResult(name = "catalogProductAttributeSetGroupRemoveResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CatalogProductAttributeSetGroupRemoveResponseParam catalogProductAttributeSetGroupRemove(
        @WebParam(name = "catalogProductAttributeSetGroupRemoveRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CatalogProductAttributeSetGroupRemoveRequestParam parameters);

    /**
     * Retrieve product types
     * 
     * @param parameters
     * @return
     *     returns magento.CatalogProductTypeListResponseParam
     */
    @WebMethod
    @WebResult(name = "catalogProductTypeListResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CatalogProductTypeListResponseParam catalogProductTypeList(
        @WebParam(name = "catalogProductTypeListRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CatalogProductTypeListRequestParam parameters);

    /**
     * Retrieve product tier prices
     * 
     * @param parameters
     * @return
     *     returns magento.CatalogProductAttributeTierPriceInfoResponseParam
     */
    @WebMethod
    @WebResult(name = "catalogProductAttributeTierPriceInfoResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CatalogProductAttributeTierPriceInfoResponseParam catalogProductAttributeTierPriceInfo(
        @WebParam(name = "catalogProductAttributeTierPriceInfoRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CatalogProductAttributeTierPriceInfoRequestParam parameters);

    /**
     * Update product tier prices
     * 
     * @param parameters
     * @return
     *     returns magento.CatalogProductAttributeTierPriceUpdateResponseParam
     */
    @WebMethod
    @WebResult(name = "catalogProductAttributeTierPriceUpdateResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CatalogProductAttributeTierPriceUpdateResponseParam catalogProductAttributeTierPriceUpdate(
        @WebParam(name = "catalogProductAttributeTierPriceUpdateRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CatalogProductAttributeTierPriceUpdateRequestParam parameters);

    /**
     * Set/Get current store view
     * 
     * @param parameters
     * @return
     *     returns magento.CatalogCategoryAttributeCurrentStoreResponseParam
     */
    @WebMethod
    @WebResult(name = "catalogCategoryAttributeCurrentStoreResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CatalogCategoryAttributeCurrentStoreResponseParam catalogCategoryAttributeCurrentStore(
        @WebParam(name = "catalogCategoryAttributeCurrentStoreRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CatalogCategoryAttributeCurrentStoreRequestParam parameters);

    /**
     * Retrieve category attributes
     * 
     * @param parameters
     * @return
     *     returns magento.CatalogCategoryAttributeListResponseParam
     */
    @WebMethod
    @WebResult(name = "catalogCategoryAttributeListResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CatalogCategoryAttributeListResponseParam catalogCategoryAttributeList(
        @WebParam(name = "catalogCategoryAttributeListRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CatalogCategoryAttributeListRequestParam parameters);

    /**
     * Retrieve attribute options
     * 
     * @param parameters
     * @return
     *     returns magento.CatalogCategoryAttributeOptionsResponseParam
     */
    @WebMethod
    @WebResult(name = "catalogCategoryAttributeOptionsResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CatalogCategoryAttributeOptionsResponseParam catalogCategoryAttributeOptions(
        @WebParam(name = "catalogCategoryAttributeOptionsRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CatalogCategoryAttributeOptionsRequestParam parameters);

    /**
     * Set/Get current store view
     * 
     * @param parameters
     * @return
     *     returns magento.CatalogProductAttributeMediaCurrentStoreResponseParam
     */
    @WebMethod
    @WebResult(name = "catalogProductAttributeMediaCurrentStoreResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CatalogProductAttributeMediaCurrentStoreResponseParam catalogProductAttributeMediaCurrentStore(
        @WebParam(name = "catalogProductAttributeMediaCurrentStoreRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CatalogProductAttributeMediaCurrentStoreRequestParam parameters);

    /**
     * Retrieve product image list
     * 
     * @param parameters
     * @return
     *     returns magento.CatalogProductAttributeMediaListResponseParam
     */
    @WebMethod
    @WebResult(name = "catalogProductAttributeMediaListResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CatalogProductAttributeMediaListResponseParam catalogProductAttributeMediaList(
        @WebParam(name = "catalogProductAttributeMediaListRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CatalogProductAttributeMediaListRequestParam parameters);

    /**
     * Retrieve product image data
     * 
     * @param parameters
     * @return
     *     returns magento.CatalogProductAttributeMediaInfoResponseParam
     */
    @WebMethod
    @WebResult(name = "catalogProductAttributeMediaInfoResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CatalogProductAttributeMediaInfoResponseParam catalogProductAttributeMediaInfo(
        @WebParam(name = "catalogProductAttributeMediaInfoRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CatalogProductAttributeMediaInfoRequestParam parameters);

    /**
     * Retrieve product image types
     * 
     * @param parameters
     * @return
     *     returns magento.CatalogProductAttributeMediaTypesResponseParam
     */
    @WebMethod
    @WebResult(name = "catalogProductAttributeMediaTypesResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CatalogProductAttributeMediaTypesResponseParam catalogProductAttributeMediaTypes(
        @WebParam(name = "catalogProductAttributeMediaTypesRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CatalogProductAttributeMediaTypesRequestParam parameters);

    /**
     * Upload new product image
     * 
     * @param parameters
     * @return
     *     returns magento.CatalogProductAttributeMediaCreateResponseParam
     */
    @WebMethod
    @WebResult(name = "catalogProductAttributeMediaCreateResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CatalogProductAttributeMediaCreateResponseParam catalogProductAttributeMediaCreate(
        @WebParam(name = "catalogProductAttributeMediaCreateRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CatalogProductAttributeMediaCreateRequestParam parameters);

    /**
     * Update product image
     * 
     * @param parameters
     * @return
     *     returns magento.CatalogProductAttributeMediaUpdateResponseParam
     */
    @WebMethod
    @WebResult(name = "catalogProductAttributeMediaUpdateResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CatalogProductAttributeMediaUpdateResponseParam catalogProductAttributeMediaUpdate(
        @WebParam(name = "catalogProductAttributeMediaUpdateRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CatalogProductAttributeMediaUpdateRequestParam parameters);

    /**
     * Remove product image
     * 
     * @param parameters
     * @return
     *     returns magento.CatalogProductAttributeMediaRemoveResponseParam
     */
    @WebMethod
    @WebResult(name = "catalogProductAttributeMediaRemoveResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CatalogProductAttributeMediaRemoveResponseParam catalogProductAttributeMediaRemove(
        @WebParam(name = "catalogProductAttributeMediaRemoveRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CatalogProductAttributeMediaRemoveRequestParam parameters);

    /**
     * Retrieve linked products
     * 
     * @param parameters
     * @return
     *     returns magento.CatalogProductLinkListResponseParam
     */
    @WebMethod
    @WebResult(name = "catalogProductLinkListResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CatalogProductLinkListResponseParam catalogProductLinkList(
        @WebParam(name = "catalogProductLinkListRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CatalogProductLinkListRequestParam parameters);

    /**
     * Assign product link
     * 
     * @param parameters
     * @return
     *     returns magento.CatalogProductLinkAssignResponseParam
     */
    @WebMethod
    @WebResult(name = "catalogProductLinkAssignResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CatalogProductLinkAssignResponseParam catalogProductLinkAssign(
        @WebParam(name = "catalogProductLinkAssignRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CatalogProductLinkAssignRequestParam parameters);

    /**
     * Update product link
     * 
     * @param parameters
     * @return
     *     returns magento.CatalogProductLinkUpdateResponseParam
     */
    @WebMethod
    @WebResult(name = "catalogProductLinkUpdateResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CatalogProductLinkUpdateResponseParam catalogProductLinkUpdate(
        @WebParam(name = "catalogProductLinkUpdateRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CatalogProductLinkUpdateRequestParam parameters);

    /**
     * Remove product link
     * 
     * @param parameters
     * @return
     *     returns magento.CatalogProductLinkRemoveResponseParam
     */
    @WebMethod
    @WebResult(name = "catalogProductLinkRemoveResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CatalogProductLinkRemoveResponseParam catalogProductLinkRemove(
        @WebParam(name = "catalogProductLinkRemoveRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CatalogProductLinkRemoveRequestParam parameters);

    /**
     * Retrieve product link types
     * 
     * @param parameters
     * @return
     *     returns magento.CatalogProductLinkTypesResponseParam
     */
    @WebMethod
    @WebResult(name = "catalogProductLinkTypesResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CatalogProductLinkTypesResponseParam catalogProductLinkTypes(
        @WebParam(name = "catalogProductLinkTypesRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CatalogProductLinkTypesRequestParam parameters);

    /**
     * Retrieve product link type attributes
     * 
     * @param parameters
     * @return
     *     returns magento.CatalogProductLinkAttributesResponseParam
     */
    @WebMethod
    @WebResult(name = "catalogProductLinkAttributesResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CatalogProductLinkAttributesResponseParam catalogProductLinkAttributes(
        @WebParam(name = "catalogProductLinkAttributesRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CatalogProductLinkAttributesRequestParam parameters);

    /**
     * Create new attribute
     * 
     * @param parameters
     * @return
     *     returns magento.CatalogProductAttributeCreateResponseParam
     */
    @WebMethod
    @WebResult(name = "catalogProductAttributeCreateResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CatalogProductAttributeCreateResponseParam catalogProductAttributeCreate(
        @WebParam(name = "catalogProductAttributeCreateRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CatalogProductAttributeCreateRequestParam parameters);

    /**
     * Delete attribute
     * 
     * @param parameters
     * @return
     *     returns magento.CatalogProductAttributeRemoveResponseParam
     */
    @WebMethod
    @WebResult(name = "catalogProductAttributeRemoveResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CatalogProductAttributeRemoveResponseParam catalogProductAttributeRemove(
        @WebParam(name = "catalogProductAttributeRemoveRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CatalogProductAttributeRemoveRequestParam parameters);

    /**
     * Retrieve list of orders by filters
     * 
     * @param parameters
     * @return
     *     returns magento.SalesOrderListResponseParam
     */
    @WebMethod
    @WebResult(name = "salesOrderListResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public SalesOrderListResponseParam salesOrderList(
        @WebParam(name = "salesOrderListRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        SalesOrderListRequestParam parameters);

    /**
     * Retrieve order information
     * 
     * @param parameters
     * @return
     *     returns magento.SalesOrderInfoResponseParam
     */
    @WebMethod
    @WebResult(name = "salesOrderInfoResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public SalesOrderInfoResponseParam salesOrderInfo(
        @WebParam(name = "salesOrderInfoRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        SalesOrderInfoRequestParam parameters);

    /**
     * Add comment to order
     * 
     * @param parameters
     * @return
     *     returns magento.SalesOrderAddCommentResponseParam
     */
    @WebMethod
    @WebResult(name = "salesOrderAddCommentResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public SalesOrderAddCommentResponseParam salesOrderAddComment(
        @WebParam(name = "salesOrderAddCommentRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        SalesOrderAddCommentRequestParam parameters);

    /**
     * Hold order
     * 
     * @param parameters
     * @return
     *     returns magento.SalesOrderHoldResponseParam
     */
    @WebMethod
    @WebResult(name = "salesOrderHoldResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public SalesOrderHoldResponseParam salesOrderHold(
        @WebParam(name = "salesOrderHoldRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        SalesOrderHoldRequestParam parameters);

    /**
     * Unhold order
     * 
     * @param parameters
     * @return
     *     returns magento.SalesOrderUnholdResponseParam
     */
    @WebMethod
    @WebResult(name = "salesOrderUnholdResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public SalesOrderUnholdResponseParam salesOrderUnhold(
        @WebParam(name = "salesOrderUnholdRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        SalesOrderUnholdRequestParam parameters);

    /**
     * Cancel order
     * 
     * @param parameters
     * @return
     *     returns magento.SalesOrderCancelResponseParam
     */
    @WebMethod
    @WebResult(name = "salesOrderCancelResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public SalesOrderCancelResponseParam salesOrderCancel(
        @WebParam(name = "salesOrderCancelRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        SalesOrderCancelRequestParam parameters);

    /**
     * Retrieve list of shipments by filters
     * 
     * @param parameters
     * @return
     *     returns magento.SalesOrderShipmentListResponseParam
     */
    @WebMethod
    @WebResult(name = "salesOrderShipmentListResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public SalesOrderShipmentListResponseParam salesOrderShipmentList(
        @WebParam(name = "salesOrderShipmentListRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        SalesOrderShipmentListRequestParam parameters);

    /**
     * Retrieve shipment information
     * 
     * @param parameters
     * @return
     *     returns magento.SalesOrderShipmentInfoResponseParam
     */
    @WebMethod
    @WebResult(name = "salesOrderShipmentInfoResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public SalesOrderShipmentInfoResponseParam salesOrderShipmentInfo(
        @WebParam(name = "salesOrderShipmentInfoRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        SalesOrderShipmentInfoRequestParam parameters);

    /**
     * Create new shipment for order
     * 
     * @param parameters
     * @return
     *     returns magento.SalesOrderShipmentCreateResponseParam
     */
    @WebMethod
    @WebResult(name = "salesOrderShipmentCreateResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public SalesOrderShipmentCreateResponseParam salesOrderShipmentCreate(
        @WebParam(name = "salesOrderShipmentCreateRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        SalesOrderShipmentCreateRequestParam parameters);

    /**
     * Add new comment to shipment
     * 
     * @param parameters
     * @return
     *     returns magento.SalesOrderShipmentAddCommentResponseParam
     */
    @WebMethod
    @WebResult(name = "salesOrderShipmentAddCommentResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public SalesOrderShipmentAddCommentResponseParam salesOrderShipmentAddComment(
        @WebParam(name = "salesOrderShipmentAddCommentRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        SalesOrderShipmentAddCommentRequestParam parameters);

    /**
     * Add new tracking number
     * 
     * @param parameters
     * @return
     *     returns magento.SalesOrderShipmentAddTrackResponseParam
     */
    @WebMethod
    @WebResult(name = "salesOrderShipmentAddTrackResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public SalesOrderShipmentAddTrackResponseParam salesOrderShipmentAddTrack(
        @WebParam(name = "salesOrderShipmentAddTrackRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        SalesOrderShipmentAddTrackRequestParam parameters);

    /**
     * Remove tracking number
     * 
     * @param parameters
     * @return
     *     returns magento.SalesOrderShipmentRemoveTrackResponseParam
     */
    @WebMethod
    @WebResult(name = "salesOrderShipmentRemoveTrackResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public SalesOrderShipmentRemoveTrackResponseParam salesOrderShipmentRemoveTrack(
        @WebParam(name = "salesOrderShipmentRemoveTrackRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        SalesOrderShipmentRemoveTrackRequestParam parameters);

    /**
     * Send shipment info
     * 
     * @param parameters
     * @return
     *     returns magento.SalesOrderShipmentSendInfoResponseParam
     */
    @WebMethod
    @WebResult(name = "salesOrderShipmentSendInfoResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public SalesOrderShipmentSendInfoResponseParam salesOrderShipmentSendInfo(
        @WebParam(name = "salesOrderShipmentSendInfoRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        SalesOrderShipmentSendInfoRequestParam parameters);

    /**
     * Retrieve list of allowed carriers for order
     * 
     * @param parameters
     * @return
     *     returns magento.SalesOrderShipmentGetCarriersResponseParam
     */
    @WebMethod
    @WebResult(name = "salesOrderShipmentGetCarriersResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public SalesOrderShipmentGetCarriersResponseParam salesOrderShipmentGetCarriers(
        @WebParam(name = "salesOrderShipmentGetCarriersRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        SalesOrderShipmentGetCarriersRequestParam parameters);

    /**
     * Retrieve list of invoices by filters
     * 
     * @param parameters
     * @return
     *     returns magento.SalesOrderInvoiceListResponseParam
     */
    @WebMethod
    @WebResult(name = "salesOrderInvoiceListResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public SalesOrderInvoiceListResponseParam salesOrderInvoiceList(
        @WebParam(name = "salesOrderInvoiceListRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        SalesOrderInvoiceListRequestParam parameters);

    /**
     * Retrieve invoice information
     * 
     * @param parameters
     * @return
     *     returns magento.SalesOrderInvoiceInfoResponseParam
     */
    @WebMethod
    @WebResult(name = "salesOrderInvoiceInfoResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public SalesOrderInvoiceInfoResponseParam salesOrderInvoiceInfo(
        @WebParam(name = "salesOrderInvoiceInfoRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        SalesOrderInvoiceInfoRequestParam parameters);

    /**
     * Create new invoice for order
     * 
     * @param parameters
     * @return
     *     returns magento.SalesOrderInvoiceCreateResponseParam
     */
    @WebMethod
    @WebResult(name = "salesOrderInvoiceCreateResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public SalesOrderInvoiceCreateResponseParam salesOrderInvoiceCreate(
        @WebParam(name = "salesOrderInvoiceCreateRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        SalesOrderInvoiceCreateRequestParam parameters);

    /**
     * Add new comment to shipment
     * 
     * @param parameters
     * @return
     *     returns magento.SalesOrderInvoiceAddCommentResponseParam
     */
    @WebMethod
    @WebResult(name = "salesOrderInvoiceAddCommentResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public SalesOrderInvoiceAddCommentResponseParam salesOrderInvoiceAddComment(
        @WebParam(name = "salesOrderInvoiceAddCommentRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        SalesOrderInvoiceAddCommentRequestParam parameters);

    /**
     * Capture invoice
     * 
     * @param parameters
     * @return
     *     returns magento.SalesOrderInvoiceCaptureResponseParam
     */
    @WebMethod
    @WebResult(name = "salesOrderInvoiceCaptureResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public SalesOrderInvoiceCaptureResponseParam salesOrderInvoiceCapture(
        @WebParam(name = "salesOrderInvoiceCaptureRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        SalesOrderInvoiceCaptureRequestParam parameters);

    /**
     * Void invoice
     * 
     * @param parameters
     * @return
     *     returns magento.SalesOrderInvoiceVoidResponseParam
     */
    @WebMethod
    @WebResult(name = "salesOrderInvoiceVoidResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public SalesOrderInvoiceVoidResponseParam salesOrderInvoiceVoid(
        @WebParam(name = "salesOrderInvoiceVoidRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        SalesOrderInvoiceVoidRequestParam parameters);

    /**
     * Cancel invoice
     * 
     * @param parameters
     * @return
     *     returns magento.SalesOrderInvoiceCancelResponseParam
     */
    @WebMethod
    @WebResult(name = "salesOrderInvoiceCancelResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public SalesOrderInvoiceCancelResponseParam salesOrderInvoiceCancel(
        @WebParam(name = "salesOrderInvoiceCancelRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        SalesOrderInvoiceCancelRequestParam parameters);

    /**
     * Retrieve list of creditmemos by filters
     * 
     * @param parameters
     * @return
     *     returns magento.SalesOrderCreditmemoListResponseParam
     */
    @WebMethod
    @WebResult(name = "salesOrderCreditmemoListResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public SalesOrderCreditmemoListResponseParam salesOrderCreditmemoList(
        @WebParam(name = "salesOrderCreditmemoListRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        SalesOrderCreditmemoListRequestParam parameters);

    /**
     * Retrieve creditmemo information
     * 
     * @param parameters
     * @return
     *     returns magento.SalesOrderCreditmemoInfoResponseParam
     */
    @WebMethod
    @WebResult(name = "salesOrderCreditmemoInfoResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public SalesOrderCreditmemoInfoResponseParam salesOrderCreditmemoInfo(
        @WebParam(name = "salesOrderCreditmemoInfoRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        SalesOrderCreditmemoInfoRequestParam parameters);

    /**
     * Create new creditmemo for order
     * 
     * @param parameters
     * @return
     *     returns magento.SalesOrderCreditmemoCreateResponseParam
     */
    @WebMethod
    @WebResult(name = "salesOrderCreditmemoCreateResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public SalesOrderCreditmemoCreateResponseParam salesOrderCreditmemoCreate(
        @WebParam(name = "salesOrderCreditmemoCreateRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        SalesOrderCreditmemoCreateRequestParam parameters);

    /**
     * Add new comment to creditmemo
     * 
     * @param parameters
     * @return
     *     returns magento.SalesOrderCreditmemoAddCommentResponseParam
     */
    @WebMethod
    @WebResult(name = "salesOrderCreditmemoAddCommentResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public SalesOrderCreditmemoAddCommentResponseParam salesOrderCreditmemoAddComment(
        @WebParam(name = "salesOrderCreditmemoAddCommentRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        SalesOrderCreditmemoAddCommentRequestParam parameters);

    /**
     * Cancel creditmemo
     * 
     * @param parameters
     * @return
     *     returns magento.SalesOrderCreditmemoCancelResponseParam
     */
    @WebMethod
    @WebResult(name = "salesOrderCreditmemoCancelResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public SalesOrderCreditmemoCancelResponseParam salesOrderCreditmemoCancel(
        @WebParam(name = "salesOrderCreditmemoCancelRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        SalesOrderCreditmemoCancelRequestParam parameters);

    /**
     * Retrieve stock data by product ids
     * 
     * @param parameters
     * @return
     *     returns magento.CatalogInventoryStockItemListResponseParam
     */
    @WebMethod
    @WebResult(name = "catalogInventoryStockItemListResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CatalogInventoryStockItemListResponseParam catalogInventoryStockItemList(
        @WebParam(name = "catalogInventoryStockItemListRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CatalogInventoryStockItemListRequestParam parameters);

    /**
     * Update product stock data
     * 
     * @param parameters
     * @return
     *     returns magento.CatalogInventoryStockItemUpdateResponseParam
     */
    @WebMethod
    @WebResult(name = "catalogInventoryStockItemUpdateResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CatalogInventoryStockItemUpdateResponseParam catalogInventoryStockItemUpdate(
        @WebParam(name = "catalogInventoryStockItemUpdateRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CatalogInventoryStockItemUpdateRequestParam parameters);

    /**
     * Create shopping cart
     * 
     * @param parameters
     * @return
     *     returns magento.ShoppingCartCreateResponseParam
     */
    @WebMethod
    @WebResult(name = "shoppingCartCreateResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public ShoppingCartCreateResponseParam shoppingCartCreate(
        @WebParam(name = "shoppingCartCreateRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        ShoppingCartCreateRequestParam parameters);

    /**
     * Retrieve information about shopping cart
     * 
     * @param parameters
     * @return
     *     returns magento.ShoppingCartInfoResponseParam
     */
    @WebMethod
    @WebResult(name = "shoppingCartInfoResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public ShoppingCartInfoResponseParam shoppingCartInfo(
        @WebParam(name = "shoppingCartInfoRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        ShoppingCartInfoRequestParam parameters);

    /**
     * Get total prices for shopping cart
     * 
     * @param parameters
     * @return
     *     returns magento.ShoppingCartTotalsResponseParam
     */
    @WebMethod
    @WebResult(name = "shoppingCartTotalsResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public ShoppingCartTotalsResponseParam shoppingCartTotals(
        @WebParam(name = "shoppingCartTotalsRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        ShoppingCartTotalsRequestParam parameters);

    /**
     * Create an order from shopping cart
     * 
     * @param parameters
     * @return
     *     returns magento.ShoppingCartOrderResponseParam
     */
    @WebMethod
    @WebResult(name = "shoppingCartOrderResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public ShoppingCartOrderResponseParam shoppingCartOrder(
        @WebParam(name = "shoppingCartOrderRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        ShoppingCartOrderRequestParam parameters);

    /**
     * Get terms and conditions
     * 
     * @param parameters
     * @return
     *     returns magento.ShoppingCartLicenseResponseParam
     */
    @WebMethod
    @WebResult(name = "shoppingCartLicenseResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public ShoppingCartLicenseResponseParam shoppingCartLicense(
        @WebParam(name = "shoppingCartLicenseRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        ShoppingCartLicenseRequestParam parameters);

    /**
     * Add product(s) to shopping cart
     * 
     * @param parameters
     * @return
     *     returns magento.ShoppingCartProductAddResponseParam
     */
    @WebMethod
    @WebResult(name = "shoppingCartProductAddResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public ShoppingCartProductAddResponseParam shoppingCartProductAdd(
        @WebParam(name = "shoppingCartProductAddRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        ShoppingCartProductAddRequestParam parameters);

    /**
     * Update product(s) quantities in shopping cart
     * 
     * @param parameters
     * @return
     *     returns magento.ShoppingCartProductUpdateResponseParam
     */
    @WebMethod
    @WebResult(name = "shoppingCartProductUpdateResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public ShoppingCartProductUpdateResponseParam shoppingCartProductUpdate(
        @WebParam(name = "shoppingCartProductUpdateRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        ShoppingCartProductUpdateRequestParam parameters);

    /**
     * Remove product(s) from shopping cart
     * 
     * @param parameters
     * @return
     *     returns magento.ShoppingCartProductRemoveResponseParam
     */
    @WebMethod
    @WebResult(name = "shoppingCartProductRemoveResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public ShoppingCartProductRemoveResponseParam shoppingCartProductRemove(
        @WebParam(name = "shoppingCartProductRemoveRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        ShoppingCartProductRemoveRequestParam parameters);

    /**
     * Get list of products in shopping cart
     * 
     * @param parameters
     * @return
     *     returns magento.ShoppingCartProductListResponseParam
     */
    @WebMethod
    @WebResult(name = "shoppingCartProductListResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public ShoppingCartProductListResponseParam shoppingCartProductList(
        @WebParam(name = "shoppingCartProductListRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        ShoppingCartProductListRequestParam parameters);

    /**
     * Move product(s) to customer quote
     * 
     * @param parameters
     * @return
     *     returns magento.ShoppingCartProductMoveToCustomerQuoteResponseParam
     */
    @WebMethod
    @WebResult(name = "shoppingCartProductMoveToCustomerQuoteResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public ShoppingCartProductMoveToCustomerQuoteResponseParam shoppingCartProductMoveToCustomerQuote(
        @WebParam(name = "shoppingCartProductMoveToCustomerQuoteRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        ShoppingCartProductMoveToCustomerQuoteRequestParam parameters);

    /**
     * Set customer for shopping cart
     * 
     * @param parameters
     * @return
     *     returns magento.ShoppingCartCustomerSetResponseParam
     */
    @WebMethod
    @WebResult(name = "shoppingCartCustomerSetResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public ShoppingCartCustomerSetResponseParam shoppingCartCustomerSet(
        @WebParam(name = "shoppingCartCustomerSetRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        ShoppingCartCustomerSetRequestParam parameters);

    /**
     * Set customer's addresses in shopping cart
     * 
     * @param parameters
     * @return
     *     returns magento.ShoppingCartCustomerAddressesResponseParam
     */
    @WebMethod
    @WebResult(name = "shoppingCartCustomerAddressesResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public ShoppingCartCustomerAddressesResponseParam shoppingCartCustomerAddresses(
        @WebParam(name = "shoppingCartCustomerAddressesRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        ShoppingCartCustomerAddressesRequestParam parameters);

    /**
     * Set shipping method
     * 
     * @param parameters
     * @return
     *     returns magento.ShoppingCartShippingMethodResponseParam
     */
    @WebMethod
    @WebResult(name = "shoppingCartShippingMethodResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public ShoppingCartShippingMethodResponseParam shoppingCartShippingMethod(
        @WebParam(name = "shoppingCartShippingMethodRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        ShoppingCartShippingMethodRequestParam parameters);

    /**
     * Get list of available shipping methods
     * 
     * @param parameters
     * @return
     *     returns magento.ShoppingCartShippingListResponseParam
     */
    @WebMethod
    @WebResult(name = "shoppingCartShippingListResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public ShoppingCartShippingListResponseParam shoppingCartShippingList(
        @WebParam(name = "shoppingCartShippingListRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        ShoppingCartShippingListRequestParam parameters);

    /**
     * Set payment method
     * 
     * @param parameters
     * @return
     *     returns magento.ShoppingCartPaymentMethodResponseParam
     */
    @WebMethod
    @WebResult(name = "shoppingCartPaymentMethodResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public ShoppingCartPaymentMethodResponseParam shoppingCartPaymentMethod(
        @WebParam(name = "shoppingCartPaymentMethodRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        ShoppingCartPaymentMethodRequestParam parameters);

    /**
     * Get list of available payment methods
     * 
     * @param parameters
     * @return
     *     returns magento.ShoppingCartPaymentListResponseParam
     */
    @WebMethod
    @WebResult(name = "shoppingCartPaymentListResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public ShoppingCartPaymentListResponseParam shoppingCartPaymentList(
        @WebParam(name = "shoppingCartPaymentListRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        ShoppingCartPaymentListRequestParam parameters);

    /**
     * Add coupon code for shopping cart
     * 
     * @param parameters
     * @return
     *     returns magento.ShoppingCartCouponAddResponseParam
     */
    @WebMethod
    @WebResult(name = "shoppingCartCouponAddResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public ShoppingCartCouponAddResponseParam shoppingCartCouponAdd(
        @WebParam(name = "shoppingCartCouponAddRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        ShoppingCartCouponAddRequestParam parameters);

    /**
     * Remove coupon code from shopping cart
     * 
     * @param parameters
     * @return
     *     returns magento.ShoppingCartCouponRemoveResponseParam
     */
    @WebMethod
    @WebResult(name = "shoppingCartCouponRemoveResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public ShoppingCartCouponRemoveResponseParam shoppingCartCouponRemove(
        @WebParam(name = "shoppingCartCouponRemoveRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        ShoppingCartCouponRemoveRequestParam parameters);

    /**
     * Retrieve list of tags by product
     * 
     * @param parameters
     * @return
     *     returns magento.CatalogProductTagListResponseParam
     */
    @WebMethod
    @WebResult(name = "catalogProductTagListResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CatalogProductTagListResponseParam catalogProductTagList(
        @WebParam(name = "catalogProductTagListRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CatalogProductTagListRequestParam parameters);

    /**
     * Retrieve product tag info
     * 
     * @param parameters
     * @return
     *     returns magento.CatalogProductTagInfoResponseParam
     */
    @WebMethod
    @WebResult(name = "catalogProductTagInfoResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CatalogProductTagInfoResponseParam catalogProductTagInfo(
        @WebParam(name = "catalogProductTagInfoRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CatalogProductTagInfoRequestParam parameters);

    /**
     * Add tag(s) to product
     * 
     * @param parameters
     * @return
     *     returns magento.CatalogProductTagAddResponseParam
     */
    @WebMethod
    @WebResult(name = "catalogProductTagAddResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CatalogProductTagAddResponseParam catalogProductTagAdd(
        @WebParam(name = "catalogProductTagAddRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CatalogProductTagAddRequestParam parameters);

    /**
     * Update product tag
     * 
     * @param parameters
     * @return
     *     returns magento.CatalogProductTagUpdateResponseParam
     */
    @WebMethod
    @WebResult(name = "catalogProductTagUpdateResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CatalogProductTagUpdateResponseParam catalogProductTagUpdate(
        @WebParam(name = "catalogProductTagUpdateRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CatalogProductTagUpdateRequestParam parameters);

    /**
     * Remove product tag
     * 
     * @param parameters
     * @return
     *     returns magento.CatalogProductTagRemoveResponseParam
     */
    @WebMethod
    @WebResult(name = "catalogProductTagRemoveResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CatalogProductTagRemoveResponseParam catalogProductTagRemove(
        @WebParam(name = "catalogProductTagRemoveRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CatalogProductTagRemoveRequestParam parameters);

    /**
     * Set a gift message to the cart
     * 
     * @param parameters
     * @return
     *     returns magento.GiftMessageForQuoteResponseParam
     */
    @WebMethod
    @WebResult(name = "giftMessageForQuoteResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public GiftMessageForQuoteResponseParam giftMessageSetForQuote(
        @WebParam(name = "giftMessageForQuoteRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        GiftMessageForQuoteRequestParam parameters);

    /**
     * Setting a gift messages to the quote item
     * 
     * @param parameters
     * @return
     *     returns magento.GiftMessageForQuoteItemResponseParam
     */
    @WebMethod
    @WebResult(name = "giftMessageForQuoteItemResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public GiftMessageForQuoteItemResponseParam giftMessageSetForQuoteItem(
        @WebParam(name = "giftMessageForQuoteItemRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        GiftMessageForQuoteItemRequestParam parameters);

    /**
     * Setting a gift messages to the quote items by products
     * 
     * @param parameters
     * @return
     *     returns magento.GiftMessageForQuoteProductResponseParam
     */
    @WebMethod
    @WebResult(name = "giftMessageForQuoteProductResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public GiftMessageForQuoteProductResponseParam giftMessageSetForQuoteProduct(
        @WebParam(name = "giftMessageForQuoteProductRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        GiftMessageForQuoteProductRequestParam parameters);

    /**
     * Add links to downloadable product
     * 
     * @param parameters
     * @return
     *     returns magento.CatalogProductDownloadableLinkAddResponseParam
     */
    @WebMethod
    @WebResult(name = "catalogProductDownloadableLinkAddResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CatalogProductDownloadableLinkAddResponseParam catalogProductDownloadableLinkAdd(
        @WebParam(name = "catalogProductDownloadableLinkAddRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CatalogProductDownloadableLinkAddRequestParam parameters);

    /**
     * Retrieve list of links and samples for downloadable product
     * 
     * @param parameters
     * @return
     *     returns magento.CatalogProductDownloadableLinkListResponseParam
     */
    @WebMethod
    @WebResult(name = "catalogProductDownloadableLinkListResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CatalogProductDownloadableLinkListResponseParam catalogProductDownloadableLinkList(
        @WebParam(name = "catalogProductDownloadableLinkListRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CatalogProductDownloadableLinkListRequestParam parameters);

    /**
     * Remove links and samples from downloadable product
     * 
     * @param parameters
     * @return
     *     returns magento.CatalogProductDownloadableLinkRemoveResponseParam
     */
    @WebMethod
    @WebResult(name = "catalogProductDownloadableLinkRemoveResponseParam", targetNamespace = "urn:Magento", partName = "parameters")
    public CatalogProductDownloadableLinkRemoveResponseParam catalogProductDownloadableLinkRemove(
        @WebParam(name = "catalogProductDownloadableLinkRemoveRequestParam", targetNamespace = "urn:Magento", partName = "parameters")
        CatalogProductDownloadableLinkRemoveRequestParam parameters);

}
